[theme]
base = "light"
primaryColor = "#1A73E8"             # Example accent color
backgroundColor = "#F5F7FA"          # Light background
secondaryBackgroundColor = "#E8EDF1" # Sidebar or widget background
textColor = "#202124"                # Dark text
font = "sans serif"

[server]
headless = true
